FROM keitaro/ckan:2.6.6-uwsgi
MAINTAINER Keitaro <info@keitaro.com>

# Install libxml2
RUN apk add --no-cache libxml2 \
        libxslt \
        libstdc++
# Setup build deps to be able to install python extensions that require build tools
RUN apk add --no-cache --virtual .build-deps \
        postgresql-dev \
        gcc \
        make \
        g++ \
        autoconf \
        automake \
        libtool \
        musl-dev \
        libxml2-dev \
        libxslt-dev \
        python-dev

RUN pip install --no-cache-dir git+https://github.com/okfn/ckanext-sentry.git#egg=ckanext-sentry && \
    pip install -e git+https://github.com/ckan/ckanext-pages.git#egg=ckanext-pages && \
    pip install --no-cache-dir git+https://github.com/ViderumGlobal/ckanext-viderum.git@v0.0.2#egg=ckanext-viderum && \
    pip install --no-cache-dir git+https://github.com/okfn/ckanext-spatial.git#egg=ckanext-spatial && \
    pip install --no-cache-dir -r https://raw.githubusercontent.com/ckan/ckanext-spatial/master/pip-requirements.txt && \
    pip install -e git+https://github.com/ckan/ckanext-geoview#egg=ckanext-geoview && \
    pip install -e git+https://github.com/ckan/ckanext-dcat.git@v0.0.7#egg=ckanext-dcat && \
    pip install -r ${APP_DIR}/src/ckanext-dcat/requirements.txt && \
    pip install -e git+https://github.com/ckan/ckanext-scheming.git@release-1.0.0#egg=ckanext-scheming && \
    pip install -r ${APP_DIR}/src/ckanext-scheming/requirements.txt && \
    pip install -e git+https://github.com/vegvesen/ckanext-dcat_ap_no.git#egg=ckanext-dcat_ap_no

# Install project extension
RUN pip install --no-cache-dir git+https://github.com/ViderumGlobal/ckanext-nav.git#egg=ckanext-nav

# Apply patches
COPY patches ${APP_DIR}/patches

RUN for d in $APP_DIR/patches/*; do \
        for f in `ls $d/*.patch | sort -g`; do \
		    cd $SRC_DIR/`basename "$d"` && echo "$0: Applying patch $f to $SRC_DIR/`basename $d`"; patch -p1 < "$f" ; \
        done ; \
    done

# Dirty fix for https://github.com/ckan/ckan/issues/3610RUN
# RUN sed -i "s/filename = re.sub(ur'-+', u'-', filename)//g" /srv/app/src/ckan/ckan/lib/munge.py

# Copy config files
COPY crontabs/* /etc/crontabs/
COPY docker-entrypoint.d/* /docker-entrypoint.d/
COPY supervisor.d/* /etc/supervisord.d/

# Load envvars plugin on ini file
# RUN paster --plugin=ckan config-tool ${APP_DIR}/production.ini "ckan.plugins = ${CKAN__PLUGINS}"
